framework:
    default_locale: en
    enabled_locales: ['en', 'pl']
    translator:
        logging: true
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
        providers:
