<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20250121113524 extends AbstractMigration
{
  public function up(Schema $schema): void
  {
    $this->addSql('CREATE SEQUENCE author_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
    $this->addSql('CREATE TABLE author (id INT NOT NULL, name VARCHAR(100) NOT NULL, surname VARCHAR(100) NOT NULL, PRIMARY KEY(id))');
    $this->addSql('CREATE TABLE author_book (author_id INT NOT NULL, book_id INT NOT NULL, PRIMARY KEY(author_id, book_id))');
    $this->addSql('CREATE INDEX IDX_2F0A2BEEF675F31B ON author_book (author_id)');
    $this->addSql('CREATE INDEX IDX_2F0A2BEE16A2B381 ON author_book (book_id)');
    $this->addSql('ALTER TABLE author_book ADD CONSTRAINT FK_2F0A2BEEF675F31B FOREIGN KEY (author_id) REFERENCES author (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE author_book ADD CONSTRAINT FK_2F0A2BEE16A2B381 FOREIGN KEY (book_id) REFERENCES books (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE books DROP author');
    $this->addSql('ALTER TABLE messenger_messages ALTER id DROP DEFAULT');
    $this->addSql('ALTER TABLE messenger_messages ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
    $this->addSql('ALTER TABLE messenger_messages ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
    $this->addSql('ALTER TABLE messenger_messages ALTER available_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
    $this->addSql('ALTER TABLE messenger_messages ALTER delivered_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
    $this->addSql('COMMENT ON COLUMN messenger_messages.created_at IS \'\'');
    $this->addSql('COMMENT ON COLUMN messenger_messages.available_at IS \'\'');
    $this->addSql('COMMENT ON COLUMN messenger_messages.delivered_at IS \'\'');
    $this->addSql('ALTER TABLE rememberme_token ALTER lastUsed TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
    $this->addSql('COMMENT ON COLUMN rememberme_token.lastUsed IS \'\'');
  }

  public function down(Schema $schema): void
  {
    $this->addSql('DROP SEQUENCE author_id_seq CASCADE');
    $this->addSql('ALTER TABLE author_book DROP CONSTRAINT FK_2F0A2BEEF675F31B');
    $this->addSql('ALTER TABLE author_book DROP CONSTRAINT FK_2F0A2BEE16A2B381');
    $this->addSql('DROP TABLE author');
    $this->addSql('DROP TABLE author_book');
    $this->addSql('ALTER TABLE books ADD author VARCHAR(255) NOT NULL');
    $this->addSql('ALTER TABLE rememberme_token ALTER lastused TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
    $this->addSql('COMMENT ON COLUMN rememberme_token.lastused IS \'(DC2Type:datetime_immutable)\'');
    $this->addSql('ALTER TABLE messenger_messages ALTER id SET DEFAULT messenger_messages_id_seq');
    $this->addSql('ALTER TABLE messenger_messages ALTER id DROP IDENTITY');
    $this->addSql('ALTER TABLE messenger_messages ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
    $this->addSql('ALTER TABLE messenger_messages ALTER available_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
    $this->addSql('ALTER TABLE messenger_messages ALTER delivered_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
    $this->addSql('COMMENT ON COLUMN messenger_messages.created_at IS \'(DC2Type:datetime_immutable)\'');
    $this->addSql('COMMENT ON COLUMN messenger_messages.available_at IS \'(DC2Type:datetime_immutable)\'');
    $this->addSql('COMMENT ON COLUMN messenger_messages.delivered_at IS \'(DC2Type:datetime_immutable)\'');
  }
}
